import type { SdkworkMallPcRouteContribution } from "@sdkwork/mall-pc-core";

export const sdkworkMallPcCommerceRoutes = [
  {
    auth: "required",
    capability: "buyer-dashboard",
    domain: "commerce",
    id: "buyer.mall.dashboard",
    packageName: "@sdkwork/mall-pc-commerce",
    path: "/buyer",
    screen: "dashboard",
    surface: "buyer",
    title: "买家中心",
    titleKey: "commerce.routes.dashboard.title",
  },
  {
    auth: "required",
    capability: "favorites",
    domain: "commerce",
    id: "buyer.mall.favorites",
    packageName: "@sdkwork/mall-pc-commerce",
    path: "/buyer/favorites",
    screen: "favorites",
    surface: "buyer",
    title: "我的收藏",
    titleKey: "commerce.routes.favorites.title",
  },
  {
    auth: "required",
    capability: "account-profile",
    domain: "commerce",
    id: "buyer.mall.profile",
    packageName: "@sdkwork/mall-pc-commerce",
    path: "/buyer/profile",
    screen: "profile",
    surface: "buyer",
    title: "个人资料",
    titleKey: "commerce.routes.profile.title",
  },
  {
    auth: "required",
    capability: "account-security",
    domain: "commerce",
    id: "buyer.mall.security",
    packageName: "@sdkwork/mall-pc-commerce",
    path: "/buyer/security",
    screen: "security",
    surface: "buyer",
    title: "账户安全",
    titleKey: "commerce.routes.security.title",
  },
  {
    auth: "required",
    capability: "gift-cards",
    domain: "commerce",
    id: "buyer.mall.gift-cards",
    packageName: "@sdkwork/mall-pc-commerce",
    path: "/buyer/gift-cards",
    screen: "gift-cards",
    surface: "buyer",
    title: "礼品卡",
    titleKey: "commerce.routes.giftCards.title",
  },
] as const satisfies readonly SdkworkMallPcRouteContribution[];
