import type { SdkworkMallPcRouteContribution } from "@sdkwork/mall-pc-core";

export const sdkworkMallPcAdminShopsRoutes = [
  {
    auth: "required",
    capability: "admin-shops",
    domain: "commerce",
    id: "admin.mall.shops",
    packageName: "@sdkwork/mall-pc-admin-shops",
    path: "/admin/shops",
    permissionHint: "commerce.shops.manage",
    screen: "shops",
    surface: "backend-admin",
    title: "商家管理",
    titleKey: "adminShops.routes.shops.title",
  },
  {
    auth: "required",
    capability: "admin-users",
    domain: "commerce",
    id: "admin.mall.users",
    packageName: "@sdkwork/mall-pc-admin-shops",
    path: "/admin/users",
    permissionHint: "commerce.users.read",
    screen: "users",
    surface: "backend-admin",
    title: "用户中心",
    titleKey: "adminShops.routes.users.title",
  },
  {
    auth: "required",
    capability: "admin-brands",
    domain: "commerce",
    id: "admin.mall.brands",
    packageName: "@sdkwork/mall-pc-admin-shops",
    path: "/admin/brands",
    permissionHint: "commerce.products.read",
    screen: "brands",
    surface: "backend-admin",
    title: "品牌中心",
    titleKey: "adminShops.routes.brands.title",
  },
  {
    auth: "required",
    capability: "admin-moderation",
    domain: "commerce",
    id: "admin.mall.moderation",
    packageName: "@sdkwork/mall-pc-admin-shops",
    path: "/admin/moderation",
    permissionHint: "commerce.risk.read",
    screen: "moderation",
    surface: "backend-admin",
    title: "举报处罚",
    titleKey: "adminShops.routes.moderation.title",
  },
] as const satisfies readonly SdkworkMallPcRouteContribution[];
