import type { SdkworkMallPcRouteContribution } from "@sdkwork/mall-pc-core";

export const sdkworkMallPcMerchantRoutes = [
  {
    auth: "required",
    capability: "merchant-dashboard",
    domain: "commerce",
    id: "merchant.mall.dashboard",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant",
    screen: "dashboard",
    surface: "merchant",
    title: "商家总览",
    titleKey: "merchant.routes.dashboard.title",
  },
  {
    auth: "required",
    capability: "merchant-onboarding",
    domain: "commerce",
    id: "merchant.mall.onboarding",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/onboarding",
    screen: "onboarding",
    surface: "merchant",
    title: "入驻申请",
    titleKey: "merchant.routes.onboarding.title",
  },
  {
    auth: "required",
    capability: "merchant-shop",
    domain: "commerce",
    id: "merchant.mall.shop",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/shop",
    screen: "shop",
    surface: "merchant",
    title: "店铺装修",
    titleKey: "merchant.routes.shop.title",
  },
  {
    auth: "required",
    capability: "merchant-products",
    domain: "commerce",
    id: "merchant.mall.products",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/products",
    screen: "products",
    surface: "merchant",
    title: "商品中心",
    titleKey: "merchant.routes.products.title",
  },
  {
    auth: "required",
    capability: "merchant-inventory",
    domain: "commerce",
    id: "merchant.mall.inventory",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/inventory",
    screen: "inventory",
    surface: "merchant",
    title: "库存管理",
    titleKey: "merchant.routes.inventory.title",
  },
  {
    auth: "required",
    capability: "merchant-orders",
    domain: "commerce",
    id: "merchant.mall.orders",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/orders",
    screen: "orders",
    surface: "merchant",
    title: "订单中心",
    titleKey: "merchant.routes.orders.title",
  },
  {
    auth: "required",
    capability: "merchant-fulfillment",
    domain: "commerce",
    id: "merchant.mall.fulfillment",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/fulfillment",
    screen: "fulfillment",
    surface: "merchant",
    title: "发货履约",
    titleKey: "merchant.routes.fulfillment.title",
  },
  {
    auth: "required",
    capability: "merchant-after-sales",
    domain: "commerce",
    id: "merchant.mall.after-sales",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/after-sales",
    screen: "after-sales",
    surface: "merchant",
    title: "售后处理",
    titleKey: "merchant.routes.afterSales.title",
  },
  {
    auth: "required",
    capability: "merchant-marketing",
    domain: "commerce",
    id: "merchant.mall.marketing",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/marketing",
    screen: "marketing",
    surface: "merchant",
    title: "营销中心",
    titleKey: "merchant.routes.marketing.title",
  },
  {
    auth: "required",
    capability: "merchant-data",
    domain: "commerce",
    id: "merchant.mall.data",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/data",
    screen: "data",
    surface: "merchant",
    title: "数据中心",
    titleKey: "merchant.routes.data.title",
  },
  {
    auth: "required",
    capability: "merchant-service",
    domain: "commerce",
    id: "merchant.mall.service",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/service",
    screen: "service",
    surface: "merchant",
    title: "客服中心",
    titleKey: "merchant.routes.service.title",
  },
  {
    auth: "required",
    capability: "merchant-settlement",
    domain: "commerce",
    id: "merchant.mall.settlement",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/settlement",
    screen: "settlement",
    surface: "merchant",
    title: "财务结算",
    titleKey: "merchant.routes.settlement.title",
  },
  {
    auth: "required",
    capability: "merchant-settings",
    domain: "commerce",
    id: "merchant.mall.settings",
    packageName: "@sdkwork/mall-pc-merchant",
    path: "/merchant/settings",
    screen: "settings",
    surface: "merchant",
    title: "设置中心",
    titleKey: "merchant.routes.settings.title",
  },
] as const satisfies readonly SdkworkMallPcRouteContribution[];
